### ISSUE TITLE
Problem while testing

### ISSUE THREAD

**Issue by akashjobanputra** [val-iisc/crowd-counting-scnn#8]
TEST dataset sorting files...
Done
Loading nets...
```
Traceback (most recent call last):
  File "test_scnn.py", line 128, in <module>
    load_nets(trained_model_files, networks)
  File "/home/akashj/workspace/other_repos/crowd-counting-scnn/src/utils.py", line 23, in load_nets
    params = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfb in position 0: ordinal not in range(128)
```

**Comment by BedirYilmaz** [comment]
Hi, this one worked for me https://stackoverflow.com/a/28218598/776348
